name = "displays"
name_pretty = "Displays"
icon = "preferences-desktop-display-randr"
global_search = false
fixed_order = true

[[entries]]
text = "Home"
icon = "akonadi-phone-home"
actions = { "select" = "hyprmon --profile home" }

[[entries]]
text = "Laptop"
icon = "computer-laptop"
actions = { "select" = "hyprmon --profile laptop" }

[[entries]]
text = "Lab"
icon = "applications-science-symbolic"
actions = { "select" = "hyprmon --profile lab" }
