name = "tools"
name_pretty = "Tools"
icon = "tools"
global_search = false
fixed_order = true

[[entries]]
text = "Screenshot"
icon = "camera-photo"
actions = { "select" = "$DOTFILES_DIRECTORY/files/scripts/screenshot" }

[[entries]]
text = "Color Picker"
icon = "gtk-color-picker"
actions = { "select" = "hyprpicker -aq" }
