templates:
  params:
    author-name: Rui Lopes
    author-email: ruilopesm19@gmail.com
    github-username: ruilopesm

install-ghc: false
system-ghc: true
compiler-check: newer-minor

ghc-options:
  "$everything": -dynamic
