#!/bin/sh

export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1
export JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export LD_PRELOAD=/usr/lib/libfreetype.so.6
cd ~/Documents/Blackboard/3rd/ADI/knime_5.2.1 && ./knime & disown
