close_when_open = true
exact_search_prefix = "'"
theme = "custom"
disable_mouse = false

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
resume_last_query = ["ctrl r"]
quick_activate = ["F1", "F2", "F3", "F4"]

[providers]
default = [
  "desktopapplications",
  "calc"
]
empty = ["desktopapplications"]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.clipboard]
time_format = "%d/%m - %H:%M"

[providers.actions]
providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" }
]

calc = [
  { action = "copy", default = true, bind = "Return" },
  { action = "save", bind = "ctrl s", after = "AsyncClearReload" },
  { action = "delete", bind = "ctrl d", after = "AsyncReload" }
]

clipboard = [
  { action = "copy", default = true, bind = "Return" },
  { action = "remove", bind = "ctrl d", after = "ClearReload" }
]
