#!/bin/sh

# scripts
sh $HOME/dotfiles/scripts/monitor-setup
sh $HOME/.config/polybar/launcher.sh

# sxhkd and bspwm
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true

# misc apps
picom & disown
blugon --setcurrent 4500
sh $HOME/.fehbg
sh $HOME/.config/polybar/launcher.sh
sh $HOME/dotfiles/scripts/emote-startup
libinput-gestures-setup autostart start

# rules
xsetroot -cursor_name left_ptr
setxkbmap pt
xbindkeys --file $HOME/.xbindkeysrc

# system tray
nm-applet & disown
blueman-applet & disown
sh $HOME/dotfiles/scripts/tailscale-systray-startup
pgrep -x Telegram >/dev/null || Telegram -startintray & disown
pgrep -x slack >/dev/null || slack -u & disown

# auth
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & disown
