#!/bin/sh

if [ -x $HOME/.config/monitor-setup.sh ]; then
    $HOME/.config/monitor-setup.sh
fi

if [ -x /usr/local/bin/polybar ]; then
    sh $HOME/.config/polybar/launcher.sh
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 12

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true

picom & disown
blugon --setcurrent 4500
sh $HOME/.fehbg

sh $HOME/.config/polybar/launcher.sh

xsetroot -cursor_name left_ptr
xbindkeys --file $HOME/.xbindkeysrc

nm-applet & disown
blueman-applet & disown

warp-cli register; warp-cli connect
