daemonize = true

max_history = 50
history_file_path = "/home/rui/.cache/clipcat/clipcatd-history"

pid_file = "/run/user/1000/clipcatd.pid"

# Controls how often the program updates its stored value of the Linux primary selection.
# In the Linux environment, the primary selection automatically updates to reflect the currently highlighted text or object,
# typically updating with every mouse movement.
primary_threshold_ms = 5000

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false

level = "INFO"

[watcher]
enable_clipboard = true
enable_primary = true

denied_text_regex_patterns = []
filter_text_min_length = 1
filter_text_max_length = 20000000

capture_image = false

[grpc]
enable_http = true
enable_local_socket = true
host = "127.0.0.1"
port = 45045
local_socket = "/run/user/1000/clipcat/grpc.sock"

[dbus]
enable = true
identifier = "instance-0"

[desktop_notification]
enable = true
timeout_ms = 2000
long_plaintext_length = 2000
