server_endpoint = "/run/user/1000/clipcat/grpc.sock"

finder = "rofi"

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false

level = "INFO"

[rofi]
line_length = 100
menu_length = 30
extra_arguments = [
    "-mesg", "Please select a clip"
]
