#!/bin/sh

export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1
export JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export LD_PRELOAD=/usr/lib/libfreetype.so.6
/home/rui/Documents/Blackboard/4th/RAS/Visual_Paradigm_17.2/bin/Visual_Paradigm & disown
